universal_import_line: "from manim_imports_ext import *"
text:
  font: "CMU Serif"
  text_alignment: "CENTER"
window:
  position_string: UR
  monitor_index: 0
  full_screen: False
camera:
  background_color: "#000000"
  resolution: (3840, 2160)
  fps: 60
  background_opacity: 1.0